### PR TITLE
Fixed console-ui bundle readme grammar

### PR DESCRIPTION
**Pull request by VividhPandey003**
Checked the Grammar of the readme file and made the required changes.
This was done to improve the overall quality of the project files.
Fixed: [Issue](https://github.com/drinksandco/symfony-console-ui/issues/19)

- [x] 👩‍🎓 I read contribution guidelines
- [x] 🐞 Pull request introduces a BC-Break
- [x] ✅ Pull request is covered by tests
- [x] 📒 Pull request is properly documented in docs

### CODE REVIEW

**Review by kpicaza — APPROVED** [review]
Thanks for contributing :raised_hands::raised_hands::raised_hands:

**Comment by kpicaza** [comment]
To make Signed commits we don't need to make a sign-off, what we need is to configure GPG keys associated with our Github account.  Check docs at https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification and https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

If you have any questions don't hesitate to ask. Thank you for contributing

**Comment by VividhPandey003** [comment]
Hey, I've set up my gpg. However could you please guide me regarding how can I signoff this pull request now

**Comment by VividhPandey003** [comment]
> To make Signed commits we don't need to make a sign-off, what we need is to configure GPG keys associated with our Github account. Check docs at https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification and https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits
> 
> If you have any questions don't hesitate to ask. Thank you for contributing

Thanks a lot @kpicaza. I have signed my commit. Thank you for helping me out and will be happy to contribute to this repository in future too.😊

**Comment by kpicaza** [comment]
Thenks @VividhPandey003 We will be  glad to see you here again :muscle::muscle::muscle:

**Comment by VividhPandey003** [comment]
Hey, @kpicaza could you please add hacktoberfest-accepted tag to my pull request.😊😊

**Pull request merged**
